---
layout: news_post
title: "$SAFE escaping vulnerability about Exception#to_s / NameError#to_s (CVE-2012-4464, CVE-2012-4466)"
author: "usa"
lang: en
---

Vulnerabilities found for Exception#to\_s, NameError#to\_s, and
name\_err\_mesg\_to\_s() which is Ruby interpreter-internal API. A
malicious user code can bypass $SAFE check by utilizing one of those
security holes.

## Details

Ruby\'s $SAFE mechanism enables untrusted user codes to run in $SAFE
&gt;= 4 mode. This is a kind of sandboxing so some operations are
restricted in that mode to protect other data outside the sandbox.

The problem found was around this mechanism. Exception#to\_s,
NameError#to\_s, and name\_err\_mesg\_to\_s() interpreter-internal API
was not correctly handling the $SAFE bits so a String object which is
not tainted can destructively be marked as tainted using them. By using
this an untrusted code in a sandbox can modify a formerly-untainted
string destructively.

Ruby 1.8 once had a [similar security issue][1]. It fixed
Exception#to\_s and NameError#to\_s, but name\_err\_mesg\_to\_str()
issue survived previous security fix.

## Affected versions

* all Ruby 1.8.7 prior to patchlevel 371
* all Ruby 1.9.3 prior to patchlevel 286
* all development branches of Ruby 2.0 prior to revision r37068

## Solution

Upgrade to a latest version.

## Credit

This vulnerability was found by Tyler Hickes.

## Updates

* Originally published at 2012-10-12 19:17:50 JST.



[1]: {{ site.url }}/en/news/2011/02/18/exception-methods-can-bypass-safe/
